# Setting the default profile as local. Can be overridden.
spring:
  profiles.active: STAGE
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_empty
    serialization.INDENT_OUTPUT: true
feign.hystrix.enabled: false
ribbon.MaxAutoRetries: 3
ribbon.MaxAutoRetriesNextServer: 3
ribbon.OkToRetryOnAllOperations: true

---
spring:
  profiles: STAGE
  jackson:
      serialization.INDENT_OUTPUT: true
---
spring:
  profiles: PROD
  jackson:
      serialization.INDENT_OUTPUT: false